# copied from https://github.com/TailorDev/docker-pandas
FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libatlas-base-dev gfortran

RUN mkdir -p /opt/pandas/build/
COPY pandas-requirements.txt /opt/pandas/build/requirements.txt
RUN pip install -r /opt/pandas/build/requirements.txt
VOLUME /data
ADD ./analyse.py /analyse.py
CMD ["python", "/analyse.py"]
