services:
  service1:
    build: ./service1
    depends_on:
      - service2
      - otel-agent
    links:
      - db
      - otel-agent
    environment:
      OTEL_AGENT: otel-agent
  service1-2:
    build: ./service1
    depends_on:
      - service2
      - otel-agent
    links:
      - db
      - otel-agent
    environment:
      OTEL_AGENT: otel-agent
  service2:
    build: ./service2
    depends_on:
      - db
      - otel-agent
    environment:
      OTEL_AGENT: otel-agent 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: service2
      MYSQL_USER: joe
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
  otel-agent:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-agent-config.yml"]
    volumes:
      - ./otel-collector-agent-config.yml:/etc/otel-collector-agent-config.yml
    links:
      - otel-collector
    depends_on:
      - otel-collector  
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - jaeger-all-in-one
    links:
      - jaeger-all-in-one
  jaeger-all-in-one:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
  client:
    links:
      - service1
      - service1-2
    depends_on:
      - service1
      - service1-2
    build:
      context: ./
      dockerfile: Dockerfile-client
  prometheus-server:    
    image: prom/prometheus:latest
    links:
      - otel-collector
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
