receivers:
  opencensus:
  otlp:
    protocols:
      grpc:      
processors:
  attributes:
    actions:
      - key: environment
        value: test
        action: insert
exporters: 
  opencensus:
    endpoint: "otel-collector:55678"
    insecure: true  
  
extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [opencensus]
    metrics:
      receivers: [opencensus]  
      exporters: [opencensus]