receivers:
  opencensus:

exporters:
  logging:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "SDK-KEY"
      "x-honeycomb-dataset": "otel-demo-python"
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [opencensus]
      processors: [batch, queued_retry]
      exporters: [jaeger, otlp]
    metrics:
      receivers: [opencensus]
      exporters: [prometheus]