{
 "title": "Django Metrics Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Django Request Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "django_exceptions" },
    { "expr": "django_request_count" },
    {
     "expr": " rate(django_request_latency_ms{quantile=\"0.99\"}[5m])\n/\n  rate(django_request_latency_ms{quantile=\"0.99\"}[5m])",
     "legendFormat": "Request Latency-{{endpoint}}-{{status}}"
    }
   ]
  },
  {
   "title": "Django Request Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "django_exceptions" },
    { "expr": "django_request_count" },
    {
     "expr": " rate(django_request_latency_ms{quantile=\"0.99\"}[5m])\n/\n  rate(django_request_latency_ms{quantile=\"0.99\"}[5m])",
     "legendFormat": "Request Latency-{{endpoint}}-{{status}}"
    }
   ]
  },
  {
   "title": "User login metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "django_user_login", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Cache metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "django_cache_localmem", "legendFormat": "{{operation}}" }
   ]
  }
 ]
}